-------------------------------------------------------TẠO INDEX--------------------------------------------------------- 
-- TẠO SECONDARY INDEX TRÊN BẢNG TAIKHOANKH
CREATE NONCLUSTERED INDEX TKKHACHHANG_TENTK ON TKKHACHHANG(TENTK) 

-- TẠO SECONDARY INDEX TRÊN BẢNG DIACHIKH
CREATE NONCLUSTERED INDEX DIACHIKH_QUAN_HUYEN ON DIACHIKH(QUAN_HUYEN)
CREATE NONCLUSTERED INDEX DIACHIKH_TINH_TP ON DIACHIKH(TINH_TP) 

-- TẠO SECONDARY INDEX TRÊN BẢNG HOADON
CREATE NONCLUSTERED INDEX HOADON_MATK ON HOADON(MATK) 
CREATE NONCLUSTERED INDEX HOADON_NGAYDAT ON HOADON(NGAYDAT) 


-- TẠO SECONDARY INDEX TRÊN BẢNG PHIEUGIAOHANG
CREATE NONCLUSTERED INDEX PGIAO_MAHD ON PHIEUGIAOHANG(MAHD) 
CREATE NONCLUSTERED INDEX PGIAO_NGGIAO ON PHIEUGIAOHANG(NGAYGIAO) 
CREATE NONCLUSTERED INDEX PGIAO_MANV ON PHIEUGIAOHANG(MANV) 

-- TẠO SECONDARYINDEX TRÊN BẢNG MATHANG
CREATE NONCLUSTERED INDEX MH_LH ON MATHANG(LOAIHANG) 
CREATE NONCLUSTERED INDEX MH_TENMH ON MATHANG(TENMH) 
CREATE NONCLUSTERED INDEX MH_THUONGHIEU ON MATHANG(THUONGHIEU) 

-- TẠO SECONDARY INDEX TRÊN BẢNG NHACUNGCAP
CREATE NONCLUSTERED INDEX NCC_TENNCC ON NHACUNGCAP(TEN_NCC) 
CREATE NONCLUSTERED INDEX NCC_MADKKD ON NHACUNGCAP(MADKKD) 

-- TẠO SECONDARY INDEX TRÊN BẢNG PHIEUGOIHANG
CREATE NONCLUSTERED INDEX PGUI_MANCC ON PHIEUGUIHANG(MA_NCC)
CREATE NONCLUSTERED INDEX PGUI_MAKHO ON PHIEUGUIHANG(MAKHO)
CREATE NONCLUSTERED INDEX PGUI_NGAYGUIDK ON PHIEUGUIHANG(NGAYGUIDK)
CREATE NONCLUSTERED INDEX PGUI_NGAYNHAP ON PHIEUGUIHANG(NGAYNHAP)





---------------------------------------------------CÁC CÂU TRUY VẤN-------------------------------------------------------
-- TÌM KIẾM TÀI KHOẢN KHÁCH HÀNG CÓ ĐỊA CHỈ LÀ Ở KHU VỰC NỘI THÀNH VÀ NGÀY ĐẶT LÀ 2018-02-14	
SELECT TK.* FROM TKKHACHHANG TK ,HOADON HD, PHIEUGIAOHANG PGH 
WHERE TK.MATK=HD.MATK AND HD.MAHD = PGH.MAHD AND PGH.KHUVUC = N'NỘI THÀNH' AND HD.NGAYDAT = '2019-09-05'

--ĐẾM SỐ HÓA ĐƠN CÓ MẶT HÀNG CÓ MẶT HÀNG LÀ LOẠI = SÁCH
SELECT COUNT (*) FROM HOADON HD,MH_HD,dbo.MATHANG MH 
WHERE HD.MAHD = dbo.MH_HD.MAHD AND MH.MAMH= MH_HD.MAMH AND MH.LOAIHANG = N'SÁCH' 


-- TÌM KIẾM LOẠI MẶT HANG MÀ NHÀ CUNG CẤP CÓ MÃ KINH DOANH SOD37205 KINH DOANH
SELECT MH.LOAIHANG FROM dbo.NHACUNGCAP NCC, MH_NCC, MATHANG MH 
WHERE NCC.MA_NCC=MH_NCC.MAMH AND MH_NCC.MAMH = MH.MAMH AND NCC.TEN_NCC = N'Varglibewentor Holdings '


